# Generated by Django 3.1.3 on 2021-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_processedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfiles',
            name='file',
            field=models.FileField(upload_to='files/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='processedfiles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
