# Generated by Django 3.1.3 on 2021-09-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210921_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfiles',
            name='fileJson',
            field=models.TextField(),
        ),
    ]
